services:
  rag-agent:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: rag-agent

    env_file:
      - .env

    restart: unless-stopped

    extra_hosts:
      - "host.docker.internal:host-gateway"

    networks:
      - default
      - rag-stack

networks:
  rag_network:
    external: true
    name: rag-stack_default
