version: "3.9"

services:
  rag-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag-agent
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - rag_network
    ports:
      - "8000:8000"

networks:
  rag_network:
    external: true
    name: rag-stack_default